// Conteúdo do app. Edite aqui para mudar receitas, guias e podcasts.
// "cor" é o fundo do card (gradiente) enquanto não houver foto.
// Para usar foto, coloque o arquivo na pasta public/ e informe em "imagem": "/nome.jpg".

export const receitas = [
  {
    id: 'tradicional',
    nome: 'Brigadeiro Tradicional',
    resumo: 'O clássico brasileiro, cremoso e com granulado.',
    emoji: '🍫',
    cor: 'linear-gradient(135deg, #5a3a1e, #2e1a0c)',
    tempo: '20 min',
    rendimento: '30 unidades',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '3 colheres (sopa) de chocolate em pó 50%',
      '1 colher (sopa) de manteiga sem sal',
      'Granulado de chocolate para enrolar',
    ],
    passos: [
      'Em uma panela, misture o leite condensado, o chocolate e a manteiga.',
      'Leve ao fogo baixo, mexendo sem parar, até desgrudar do fundo da panela (cerca de 10 min).',
      'Despeje em um prato untado com manteiga e deixe esfriar completamente.',
      'Unte as mãos com manteiga, enrole bolinhas e passe no granulado.',
      'Coloque em forminhas e sirva.',
    ],
    dicas: 'Para brigadeiro gourmet, use chocolate em pó 50% ou 70% e chocolate nobre ralado no lugar do granulado.',
  },
  {
    id: 'beijinho',
    nome: 'Beijinho de Coco',
    resumo: 'Doce e delicado, com coco fresco e um cravo.',
    emoji: '🥥',
    cor: 'linear-gradient(135deg, #f5e9dc, #d9c1a6)',
    tempo: '20 min',
    rendimento: '30 unidades',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '1 colher (sopa) de manteiga sem sal',
      '100 g de coco ralado',
      'Coco ralado ou açúcar cristal para enrolar',
      'Cravos-da-índia para decorar',
    ],
    passos: [
      'Misture o leite condensado, a manteiga e o coco em uma panela.',
      'Cozinhe em fogo baixo, mexendo sempre, até desgrudar do fundo.',
      'Transfira para um prato untado e deixe esfriar.',
      'Enrole as bolinhas, passe no coco e finalize com um cravo.',
    ],
    dicas: 'Use coco fresco ralado para um sabor muito mais intenso.',
  },
  {
    id: 'ninho',
    nome: 'Brigadeiro de Ninho',
    resumo: 'Cremoso, com leite em pó e cobertura branca.',
    emoji: '🥛',
    cor: 'linear-gradient(135deg, #fff6e8, #f0d9b5)',
    tempo: '25 min',
    rendimento: '30 unidades',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '4 colheres (sopa) de leite em pó',
      '1 colher (sopa) de manteiga sem sal',
      '1 caixinha de creme de leite (200 g)',
      'Leite em pó para enrolar',
    ],
    passos: [
      'Misture o leite condensado, o leite em pó e a manteiga na panela.',
      'Cozinhe em fogo baixo mexendo sempre até engrossar bem.',
      'Desligue o fogo e misture o creme de leite.',
      'Deixe esfriar, enrole e passe no leite em pó.',
    ],
    dicas: 'Recheie com uma framboesa ou pedaço de morango para uma versão gourmet.',
  },
  {
    id: 'pistache',
    nome: 'Brigadeiro de Pistache',
    resumo: 'Sofisticado, com pasta de pistache e crocante.',
    emoji: '💚',
    cor: 'linear-gradient(135deg, #a7c957, #6a994e)',
    tempo: '30 min',
    rendimento: '25 unidades',
    dificuldade: 'Média',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '2 colheres (sopa) de pasta de pistache',
      '1 colher (sopa) de manteiga sem sal',
      '1 caixinha de creme de leite (200 g)',
      'Pistache picado para enrolar',
    ],
    passos: [
      'Misture o leite condensado, a pasta de pistache e a manteiga.',
      'Cozinhe em fogo baixo até desgrudar do fundo da panela.',
      'Fora do fogo, incorpore o creme de leite.',
      'Deixe esfriar, enrole e passe no pistache picado.',
    ],
    dicas: 'A pasta de pistache pura (sem açúcar) dá o melhor resultado.',
  },
  {
    id: 'morango',
    nome: 'Brigadeiro de Morango',
    resumo: 'Sabor de fruta com cor rosa natural.',
    emoji: '🍓',
    cor: 'linear-gradient(135deg, #ff7eb3, #c9184a)',
    tempo: '25 min',
    rendimento: '30 unidades',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '3 colheres (sopa) de morango desidratado em pó (ou gelatina de morango)',
      '1 colher (sopa) de manteiga sem sal',
      'Açúcar cristal rosa para enrolar',
    ],
    passos: [
      'Misture tudo na panela e leve ao fogo baixo.',
      'Mexa até desgrudar do fundo.',
      'Esfrie, enrole e passe no açúcar cristal.',
    ],
    dicas: 'Um pedacinho de morango fresco no centro faz toda a diferença.',
  },
  {
    id: 'cafe',
    nome: 'Brigadeiro de Café',
    resumo: 'Chocolate meio amargo com espresso.',
    emoji: '☕',
    cor: 'linear-gradient(135deg, #6f4e37, #3b2314)',
    tempo: '20 min',
    rendimento: '30 unidades',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '2 colheres (sopa) de chocolate em pó 50%',
      '1 colher (sopa) de café solúvel',
      '1 colher (sopa) de manteiga sem sal',
      'Chocolate meio amargo ralado para enrolar',
    ],
    passos: [
      'Dissolva o café em 1 colher de água quente.',
      'Misture com os demais ingredientes na panela.',
      'Cozinhe em fogo baixo até desgrudar do fundo.',
      'Esfrie, enrole e passe no chocolate ralado.',
    ],
    dicas: 'Grãos de café cobertos com chocolate são uma decoração linda.',
  },
]

export const guia = {
  recheios: [
    {
      id: 'nutella',
      nome: 'Creme de avelã',
      descricao: 'Um pouco de creme de avelã no centro do brigadeiro. Congele porções pequenas antes de rechear.',
      emoji: '🌰',
      cor: 'linear-gradient(135deg, #7b4a2d, #4a2a17)',
    },
    {
      id: 'frutas',
      nome: 'Frutas frescas',
      descricao: 'Morango, framboesa ou uva. Seque bem a fruta e monte no mesmo dia.',
      emoji: '🍇',
      cor: 'linear-gradient(135deg, #d63384, #7b2cbf)',
    },
    {
      id: 'caramelo',
      nome: 'Caramelo salgado',
      descricao: 'Doce de leite firme ou caramelo com flor de sal. Combina com brigadeiro tradicional.',
      emoji: '🍯',
      cor: 'linear-gradient(135deg, #f4a261, #b5651d)',
    },
    {
      id: 'licor',
      nome: 'Licores',
      descricao: 'Cerca de 1 colher (sopa) de licor na massa: Baileys, Amarula, Rum.',
      emoji: '🥃',
      cor: 'linear-gradient(135deg, #8d5524, #3e2614)',
    },
  ],
  coberturas: [
    {
      id: 'granulado-belga',
      nome: 'Granulado belga',
      descricao: 'Feito de chocolate de verdade. Derrete na boca, diferente do granulado comum.',
      emoji: '✨',
      cor: 'linear-gradient(135deg, #3e2614, #1f1108)',
    },
    {
      id: 'chocolate-ralado',
      nome: 'Chocolate ralado',
      descricao: 'Rale chocolate nobre gelado com o lado grosso do ralador.',
      emoji: '🍫',
      cor: 'linear-gradient(135deg, #5a3a1e, #2e1a0c)',
    },
    {
      id: 'castanhas',
      nome: 'Castanhas e nozes',
      descricao: 'Pistache, amêndoa, castanha de caju ou avelã picadas e levemente tostadas.',
      emoji: '🥜',
      cor: 'linear-gradient(135deg, #c8a97e, #8a6a44)',
    },
    {
      id: 'acucar-cristal',
      nome: 'Açúcar cristal colorido',
      descricao: 'Brilho e cor. Ótimo para beijinho e brigadeiros de frutas.',
      emoji: '🌈',
      cor: 'linear-gradient(135deg, #ff9a9e, #fad0c4)',
    },
    {
      id: 'flor-de-sal',
      nome: 'Flor de sal',
      descricao: 'Poucos cristais por cima realçam o chocolate. Use com moderação.',
      emoji: '🧂',
      cor: 'linear-gradient(135deg, #e0e0e0, #9e9e9e)',
    },
  ],
}

// Para adicionar áudio, coloque o arquivo em public/ e informe "audio": "/episodio-1.mp3".
export const podcasts = [
  {
    id: 'ep1',
    titulo: 'Fundamentos do brigadeiro gourmet',
    descricao: 'Ponto certo, ingredientes de qualidade e os erros mais comuns.',
    duracao: '18 min',
    audio: null,
  },
  {
    id: 'ep2',
    titulo: 'Como precificar seus doces',
    descricao: 'Custo dos ingredientes, tempo de trabalho e margem de lucro.',
    duracao: '22 min',
    audio: null,
  },
  {
    id: 'ep3',
    titulo: 'Embalagens que vendem',
    descricao: 'Caixas, forminhas e apresentação para encantar o cliente.',
    duracao: '15 min',
    audio: null,
  },
]
