// Conteúdo do app. Edite aqui para mudar receitas, guias e podcasts.
// "cor" é o fundo do card (gradiente) enquanto não houver foto.
// Para usar foto, coloque o arquivo na pasta public/ e informe em "imagem": "/nome.jpg".

export const receitas = [
  {
    id: 'tradicional',
    nome: 'Brigadeiro Tradicional',
    resumo: 'O clássico brasileiro: cremoso, no ponto certo de enrolar e coberto de granulado.',
    emoji: '🍫',
    cor: 'linear-gradient(135deg, #5a3a1e, #2e1a0c)',
    imagem: '/brigatradi.webp',
    fotoReceita: '/receitatradi.webp',
    tempo: '15 min + 2h de descanso',
    rendimento: '25 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '3 colheres (sopa) de chocolate em pó 50%, peneirado',
      '1 colher (sopa) de manteiga sem sal',
      '1 pitada de sal (opcional, realça o chocolate)',
      'Granulado de chocolate para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, misture o leite condensado com o chocolate peneirado ainda com o fogo desligado, até não sobrar nenhum grumo. Junte a manteiga e o sal.',
      'Leve ao fogo baixo, mexendo sem parar com uma espátula de silicone e raspando bem o fundo e as laterais.',
      'Cozinhe por 10 a 12 minutos. O ponto certo é quando você inclina a panela e a massa desliza inteira, num bloco só, e o fundo fica visível por alguns segundos.',
      'Transfira para um prato untado com manteiga e cubra com filme plástico encostado na superfície, para não formar casquinha. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos com manteiga e enrole bolinhas de cerca de 15 g (uma colher de chá bem cheia). Passe no granulado.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para uma versão gourmet, troque o chocolate em pó por 150 g de chocolate meio amargo picado e acrescente 2 colheres (sopa) de creme de leite. Enrole no granulado belga ou em chocolate nobre raspado.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente, em pote fechado, e até 7 dias na geladeira. Tire da geladeira 20 minutos antes de servir.',
  },
  {
    id: 'beijinho',
    nome: 'Beijinho de Coco',
    resumo: 'Doce, macio e perfumado de coco, com o tradicional cravo por cima.',
    emoji: '🥥',
    cor: 'linear-gradient(135deg, #f5e9dc, #d9c1a6)',
    imagem: '/brigacoco.webp',
    fotoReceita: '/receitacoco.webp',
    tempo: '15 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '1 colher (sopa) de manteiga sem sal',
      '100 g de coco ralado seco, sem açúcar',
      '3 colheres (sopa) de leite, para hidratar o coco',
      'Açúcar cristal ou coco ralado para enrolar',
      'Cravos-da-índia para decorar',
      'Manteiga para untar',
    ],
    passos: [
      'Misture o coco ralado com o leite e deixe descansar por 10 minutos, para hidratar.',
      'Numa panela de fundo grosso, junte o leite condensado, a manteiga e o coco hidratado.',
      'Cozinhe em fogo baixo, mexendo sem parar e raspando bem o fundo, por 10 a 12 minutos. O ponto é quando a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante. O beijinho fica um pouco mais mole que o brigadeiro, e isso é normal.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar cristal ou no coco ralado.',
      'Espete um cravo no topo de cada um e coloque em forminhas nº 4.',
    ],
    dicas:
      'Quer um sabor mais intenso? Use coco fresco ralado no lugar do seco e dispense o leite. Como ele solta mais água, cozinhe de 3 a 5 minutos a mais até dar o ponto.',
    atencao: 'O cravo é só decoração. Avise quem for comer para retirá-lo antes.',
    conservacao:
      'Com coco seco, dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Com coco fresco, dura só 2 dias fora da geladeira.',
  },
  {
    id: 'ninho',
    nome: 'Brigadeiro de Ninho',
    resumo: 'Cremoso, com sabor suave de leite e envolto em leite em pó.',
    emoji: '🥛',
    cor: 'linear-gradient(135deg, #fff6e8, #f0d9b5)',
    imagem: '/briganinho.webp',
    fotoReceita: '/receitaninho.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '30 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '4 colheres (sopa) de leite em pó, peneirado',
      '½ caixinha de creme de leite (100 g)',
      '1 colher (sopa) de manteiga sem sal',
      'Leite em pó peneirado para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Com o fogo ainda desligado, misture na panela o leite condensado e o leite em pó peneirado até ficar liso, sem grumos.',
      'Junte o creme de leite e a manteiga e leve ao fogo baixo.',
      'Cozinhe mexendo sem parar e raspando bem o fundo, por 12 a 15 minutos. O ponto é quando a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no leite em pó.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para uma versão gourmet, achate a bolinha na palma da mão, coloque uma framboesa ou um pedaço de morango no centro e feche. Com fruta fresca, o doce deve ficar na geladeira e ser consumido em até 2 dias.',
    conservacao:
      'Sem fruta, dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. O leite em pó da cobertura absorve umidade com o tempo, então, para vender ou servir em festa, passe as bolinhas nele o mais perto possível da hora de servir.',
  },
  {
    id: 'pistache',
    nome: 'Brigadeiro de Pistache',
    resumo: 'Sofisticado, com sabor intenso de pistache e cobertura crocante.',
    emoji: '💚',
    cor: 'linear-gradient(135deg, #a7c957, #6a994e)',
    imagem: '/brigapista.webp',
    fotoReceita: '/receitapista.webp',
    tempo: '25 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Média',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '½ caixinha de creme de leite (100 g)',
      '1 colher (sopa) de manteiga sem sal',
      '60 g de pasta de pistache pura (cerca de 3 colheres de sopa cheias)',
      'Pistache sem sal, picado, para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, misture o leite condensado, o creme de leite e a manteiga.',
      'Leve ao fogo baixo, mexendo sem parar e raspando bem o fundo, por cerca de 10 minutos, até começar a engrossar.',
      'Acrescente a pasta de pistache e continue mexendo por mais 3 a 5 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no pistache picado, pressionando levemente para aderir.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Prefira a pasta de pistache pura, sem açúcar, com 100% pistache no rótulo. A cor natural é verde-oliva: se quiser um verde mais vivo, use uma gota de corante alimentício em gel, nunca líquido, porque ele altera a textura.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Para manter o pistache da cobertura crocante, guarde em pote bem fechado.',
  },
  {
    id: 'morango',
    nome: 'Brigadeiro de Morango',
    resumo: 'Sabor de fruta de verdade, com cor rosa natural e casquinha de açúcar cristal.',
    emoji: '🍓',
    cor: 'linear-gradient(135deg, #ff7eb3, #c9184a)',
    imagem: '/brigamoran.webp',
    fotoReceita: '/receitamoran.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '25 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '3 colheres (sopa) de morango liofilizado (desidratado) em pó, peneirado',
      '1 colher (sopa) de manteiga sem sal',
      'Açúcar cristal para enrolar (branco ou rosa)',
      'Manteiga para untar',
    ],
    passos: [
      'Com o fogo ainda desligado, misture na panela o leite condensado e o morango em pó peneirado até dissolver bem e não sobrar grumos. Junte a manteiga.',
      'Leve ao fogo baixo, mexendo sem parar e raspando bem o fundo e as laterais.',
      'Cozinhe por 10 a 12 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar cristal.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    variacao: {
      titulo: 'Variação com gelatina',
      texto:
        'Troque o morango em pó por 1 envelope de gelatina de morango (cerca de 25 g), dissolvido no leite condensado frio antes de ir ao fogo. A cor fica mais viva, a massa mais firme e o sabor lembra bala de morango. Nessa versão, a cor não é natural.',
    },
    dicas:
      'Para surpreender, achate a bolinha na mão, coloque um pedacinho de morango fresco bem sequinho no centro e feche. Com fruta fresca, guarde na geladeira e consuma em até 2 dias.',
    conservacao: 'Sem fruta, dura até 3 dias em temperatura ambiente e até 7 dias na geladeira.',
  },
  {
    id: 'cafe',
    nome: 'Brigadeiro de Café',
    resumo: 'Chocolate e café na medida, com aroma intenso e cobertura de chocolate meio amargo.',
    emoji: '☕',
    cor: 'linear-gradient(135deg, #6f4e37, #3b2314)',
    imagem: '/brigacafe.webp',
    fotoReceita: '/receitacafe.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '25 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '2 colheres (sopa) de chocolate em pó 50%, peneirado',
      '1 colher (sopa) de café solúvel',
      '1 colher (sopa) de água quente',
      '1 colher (sopa) de manteiga sem sal',
      'Chocolate meio amargo ralado para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Dissolva o café solúvel na água quente até não sobrar nenhum grão.',
      'Com o fogo ainda desligado, misture na panela o leite condensado, o chocolate em pó e o café dissolvido até ficar liso. Junte a manteiga.',
      'Leve ao fogo baixo, mexendo sem parar e raspando bem o fundo, por 10 a 12 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no chocolate ralado.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    variacao: {
      titulo: 'Variação com espresso',
      texto:
        'Troque o café solúvel e a água por 2 colheres (sopa) de espresso bem forte. O sabor fica mais redondo, mas a massa leva de 2 a 3 minutos a mais para dar o ponto.',
    },
    dicas:
      'Finalize cada brigadeiro com um grão de café coberto de chocolate. Fica lindo na bandeja e avisa, só de olhar, qual é o sabor.',
    atencao:
      'Contém cafeína. Não é indicado para crianças pequenas, então identifique bem na mesa de festa.',
    conservacao: 'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira.',
  },
  {
    id: 'branco',
    nome: 'Brigadeiro Branco',
    resumo: 'Delicado e cremoso, feito com chocolate branco de verdade.',
    emoji: '🤍',
    cor: 'linear-gradient(135deg, #fffaf3, #e8d9c4)',
    imagem: '/brigabranco.webp',
    fotoReceita: '/receitabranco.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '100 g de chocolate branco nobre picado',
      '1 colher (sopa) de manteiga sem sal',
      'Chocolate branco ralado ou granulado branco para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, junte o leite condensado e a manteiga e leve ao fogo baixo.',
      'Cozinhe mexendo sem parar e raspando bem o fundo, por 8 a 10 minutos, até engrossar e o fundo da panela aparecer rapidamente ao passar a espátula. Nesse momento, a massa ainda deve estar um pouco mais mole que o ponto de brigadeiro.',
      'Desligue o fogo e junte o chocolate branco picado. Mexa até derreter completamente e a massa ficar lisa e brilhante. Ela vai firmar e chegar ao ponto com o chocolate.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe na cobertura.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'É a base perfeita para colorir e combinar com o tema da festa. Use corante alimentício em gel, nunca líquido, e misture junto com o chocolate, no passo 3. Comece com a ponta de um palito e vá aumentando aos poucos: os tons ficam pastel e lindos em bandeja.',
    nota: {
      titulo: 'Para ficar mais branquinho',
      texto:
        'Cozinhe sempre em fogo baixo e não passe do tempo, porque quanto mais o leite condensado cozinha, mais ele escurece. A cor natural é marfim, e isso é normal.',
    },
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Em dias quentes, prefira a geladeira, porque o chocolate branco amolece fácil.',
  },
  {
    id: 'churros',
    nome: 'Brigadeiro de Churros',
    resumo: 'Doce de leite e canela, igual ao churros da feira.',
    emoji: '🍩',
    cor: 'linear-gradient(135deg, #d9a066, #8a5a2b)',
    imagem: '/brigachurro.webp',
    fotoReceita: '/receitachurro.webp',
    tempo: '25 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '100 g de doce de leite cremoso (cerca de 4 colheres de sopa cheias)',
      '1 colher (sopa) de manteiga sem sal',
      '½ colher (chá) de canela em pó',
      '1 pitada de sal (opcional, realça o doce de leite)',
      'Manteiga para untar',
    ],
    paraEnrolar: ['½ xícara (chá) de açúcar refinado', '1 colher (chá) de canela em pó'],
    passos: [
      'Numa panela de fundo grosso, misture o leite condensado, a manteiga, a canela e o sal.',
      'Leve ao fogo baixo e cozinhe mexendo sem parar, raspando bem o fundo, por cerca de 8 minutos.',
      'Junte o doce de leite e continue mexendo por mais 5 a 7 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante. Não pare de mexer nessa fase, porque o doce de leite pega no fundo com facilidade.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Misture o açúcar e a canela da cobertura num prato fundo.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar com canela.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para surpreender na mordida, achate a bolinha na mão, coloque um cubinho de doce de leite de corte no centro e feche bem antes de passar no açúcar.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. O açúcar da cobertura pode umedecer na geladeira, então, se precisar, passe as bolinhas nele de novo antes de servir.',
  },
  {
    id: 'pacoca',
    nome: 'Brigadeiro de Paçoca',
    resumo: 'Sabor de amendoim com cara de festa junina.',
    emoji: '🥜',
    cor: 'linear-gradient(135deg, #e0b877, #9c6b3c)',
    imagem: '/brigapacoca.webp',
    fotoReceita: '/receitapacoca.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '4 paçocas de rolha bem esfareladas (cerca de 80 g)',
      '1 colher (sopa) de manteiga sem sal',
      '1 pitada de sal',
      '4 paçocas de rolha esfareladas para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, junte o leite condensado, a manteiga e o sal e leve ao fogo baixo, mexendo sem parar, por cerca de 5 minutos.',
      'Acrescente a paçoca esfarelada e continue mexendo, raspando bem o fundo, por mais 5 a 7 minutos. Com a paçoca, a massa engrossa rápido, então fique de olho.',
      'O ponto é quando a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante. Desligue o fogo.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe na paçoca esfarelada, pressionando levemente para aderir.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Esfarele bem a paçoca da massa, quase em pó, para o brigadeiro ficar liso. Já a da cobertura pode ficar em pedacinhos, para dar crocância.',
    atencao:
      'Contém amendoim, um alérgeno forte. Na mesa de festa, identifique bem e deixe em forminha de cor diferente, para ninguém pegar por engano.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. A cobertura de paçoca fica mais crocante em pote bem fechado, fora da geladeira.',
  },
  {
    id: 'maracuja',
    nome: 'Brigadeiro de Maracujá',
    resumo: 'Azedinho na medida, refrescante e cremoso.',
    emoji: '🍋',
    cor: 'linear-gradient(135deg, #ffd166, #e09f1f)',
    imagem: '/brigamaracu.webp',
    fotoReceita: '/receitamaracu.webp',
    tempo: '30 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Média',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '80 g de chocolate branco nobre picado',
      '½ xícara (chá) de suco natural de maracujá, coado e sem água (a polpa de cerca de 3 maracujás)',
      '1 colher (sopa) de manteiga sem sal',
      'Açúcar cristal para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panelinha, leve o suco ao fogo baixo e deixe reduzir até sobrarem cerca de 4 colheres (sopa), por 5 a 7 minutos. Reserve.',
      'Numa panela de fundo grosso, junte o leite condensado e a manteiga e cozinhe em fogo baixo, mexendo sem parar, por cerca de 5 minutos, até começar a engrossar.',
      'Acrescente o suco reduzido aos poucos, mexendo bem. Continue cozinhando por mais 5 a 7 minutos, até o fundo da panela aparecer rapidamente ao passar a espátula. A massa ainda deve estar um pouco mais mole que o ponto de brigadeiro.',
      'Desligue o fogo, junte o chocolate branco e mexa até derreter completamente. A massa vai firmar e chegar ao ponto com o chocolate.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar cristal.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para decorar, coloque algumas sementes de maracujá por cima de cada brigadeiro. Faça isso perto da hora de servir, porque elas soltam umidade. Brigadeiros decorados com sementes devem ficar na geladeira e ser consumidos em até 2 dias.',
    conservacao: 'Sem as sementes, dura até 3 dias em temperatura ambiente e até 7 dias na geladeira.',
  },
  {
    id: 'limao',
    nome: 'Brigadeiro de Limão',
    resumo: 'Leve, cítrico e perfumado.',
    emoji: '🍈',
    cor: 'linear-gradient(135deg, #c5e384, #6a994e)',
    imagem: '/brigalimao.webp',
    fotoReceita: '/receitalimao.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '25 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '1 colher (sopa) de manteiga sem sal',
      'Raspas de 1 limão tahiti (só a parte verde)',
      '2 colheres (sopa) de suco de limão tahiti, coado',
      'Açúcar cristal para enrolar',
      'Raspas de limão para decorar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, leve o leite condensado e a manteiga ao fogo baixo, mexendo sem parar e raspando bem o fundo.',
      'Cozinhe por 12 a 14 minutos, até passar um pouco do ponto de brigadeiro: a massa desliza inteira ao inclinar a panela e o fundo fica visível por alguns segundos. Esse ponto mais firme compensa o suco que entra depois.',
      'Desligue o fogo e junte o suco e as raspas de limão. Mexa bem: a massa vai amolecer um pouco e ficar mais cremosa.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar cristal.',
      'Coloque em forminhas nº 4 e decore com raspinhas de limão perto da hora de servir.',
    ],
    dicas:
      'Rale só a parte verde da casca, porque a parte branca deixa o doce amargo. Lave e seque bem o limão antes de ralar.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Se for guardar, deixe para decorar com as raspas só na hora de servir.',
  },
  {
    id: 'avela',
    nome: 'Brigadeiro de Avelã',
    resumo: 'Cremoso, com creme de avelã, chocolate e cobertura crocante.',
    emoji: '🌰',
    cor: 'linear-gradient(135deg, #8b5a3c, #4a2a17)',
    imagem: '/brigaavela.webp',
    fotoReceita: '/receitaavela.webp',
    tempo: '25 min + 2h de descanso',
    rendimento: '28 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '100 g de creme de avelã (cerca de 4 colheres de sopa cheias)',
      '1 colher (sopa) de chocolate em pó 50%, peneirado',
      '1 colher (sopa) de manteiga sem sal',
      '80 g de avelãs torradas e trituradas para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Se as avelãs forem cruas, torre em forno a 180 °C por 8 a 10 minutos. Ainda quentes, esfregue num pano de prato para soltar a pelinha. Deixe esfriar e triture grosseiramente.',
      'Com o fogo ainda desligado, misture na panela o leite condensado, o chocolate em pó e a manteiga até ficar liso.',
      'Leve ao fogo baixo e cozinhe mexendo sem parar, raspando bem o fundo, por cerca de 6 minutos.',
      'Junte o creme de avelã e continue mexendo por mais 5 a 7 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe nas avelãs trituradas, pressionando levemente para aderir.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para um efeito de bombom, achate a bolinha na mão, coloque uma avelã torrada inteira no centro e feche antes de passar na cobertura.',
    atencao:
      'Contém avelã, uma oleaginosa com alto risco de alergia. Na mesa de festa, identifique bem e deixe em forminha de cor diferente.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Guarde em pote bem fechado, para a avelã da cobertura continuar crocante.',
  },
  {
    id: 'biscoito',
    nome: 'Brigadeiro de Biscoito',
    resumo: 'Branquinho e cremoso, com pedacinhos de biscoito de chocolate.',
    emoji: '🍪',
    cor: 'linear-gradient(135deg, #f4efe8, #6b6b6b)',
    imagem: '/brigabiscoito.webp',
    fotoReceita: '/receitabiscoito.webp',
    tempo: '30 min + 2h de descanso',
    rendimento: '32 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '1 caixinha de creme de leite (200 g)',
      '1 colher (sopa) de manteiga sem sal',
      '4 biscoitos recheados de chocolate, picados em pedacinhos (para a massa)',
      '6 biscoitos recheados de chocolate, triturados finos com o recheio (para enrolar)',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, junte o leite condensado, o creme de leite e a manteiga e leve ao fogo baixo.',
      'Cozinhe mexendo sem parar e raspando bem o fundo, por 18 a 20 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Desligue o fogo, espere 5 minutos e misture os biscoitos picados, sem mexer demais, para os pedacinhos não se desmancharem.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no biscoito triturado fino.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para a massa ficar branquinha, pique o biscoito com faca, em pedacinhos, em vez de triturar no liquidificador: o pó do biscoito escurece tudo. Já para a cobertura, triture fino junto com o recheio, porque o recheio ajuda o farelo a grudar na bolinha.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 5 dias na geladeira. Os pedacinhos de biscoito da massa amolecem com o tempo, então ele fica mais gostoso nos primeiros 2 dias.',
  },
  {
    id: 'doce-de-leite',
    nome: 'Brigadeiro de Doce de Leite',
    resumo: 'Caramelado e com gostinho de fazenda.',
    emoji: '🍯',
    cor: 'linear-gradient(135deg, #e8a959, #a86a1f)',
    imagem: '/brigadoce.webp',
    fotoReceita: '/receitadoce.webp',
    tempo: '25 min + 2h de descanso',
    rendimento: '32 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '200 g de doce de leite cremoso',
      '1 colher (sopa) de manteiga sem sal',
      'Açúcar cristal ou castanha-de-caju picada para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Numa panela de fundo grosso, leve o leite condensado e a manteiga ao fogo baixo, mexendo sem parar, por cerca de 5 minutos.',
      'Acrescente o doce de leite e continue mexendo e raspando bem o fundo por mais 8 a 10 minutos. Não pare de mexer nessa fase, porque o doce de leite pega no fundo com facilidade.',
      'O ponto é quando a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante. Desligue o fogo.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe na cobertura escolhida, pressionando levemente se for castanha.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Para transformar em brigadeiro de caramelo salgado, enrole no açúcar cristal e coloque alguns cristais de flor de sal por cima de cada um, perto da hora de servir, porque ela derrete com a umidade.',
    atencao:
      'A versão com castanha contém oleaginosa, um alérgeno forte. Na mesa de festa, identifique bem e deixe em forminha de cor diferente.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Guarde em pote bem fechado, para a castanha continuar crocante.',
  },
  {
    id: 'belga',
    nome: 'Brigadeiro Gourmet Belga',
    resumo: 'Feito com chocolate nobre: sabor intenso e textura aveludada.',
    emoji: '✨',
    cor: 'linear-gradient(135deg, #3e2614, #120906)',
    imagem: '/brigabelga.webp',
    fotoReceita: '/receitabelga.webp',
    tempo: '25 min + 3h de descanso',
    rendimento: '25 unidades (20 g)',
    dificuldade: 'Média',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '½ caixinha de creme de leite (100 g)',
      '1 colher (sopa) de cacau em pó 100%, peneirado',
      '1 colher (sopa) de manteiga sem sal',
      '100 g de chocolate belga meio amargo picado',
      'Granulado belga ou chocolate meio amargo raspado para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Com o fogo ainda desligado, misture na panela o leite condensado, o creme de leite e o cacau peneirado até ficar liso. Junte a manteiga.',
      'Leve ao fogo baixo e cozinhe mexendo sem parar e raspando bem o fundo, por 12 a 15 minutos, até o fundo da panela aparecer rapidamente ao passar a espátula. A massa ainda deve estar um pouco mais mole que o ponto de brigadeiro.',
      'Desligue o fogo e junte o chocolate picado. Mexa até derreter completamente e a massa ficar lisa e brilhante. Ela vai firmar e chegar ao ponto com o chocolate.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe descansar em temperatura ambiente por pelo menos 3 horas, ou de um dia para o outro para uma textura ainda melhor.',
      'Unte as mãos, enrole bolinhas de cerca de 20 g e passe no granulado belga, pressionando levemente para aderir.',
      'Coloque em forminhas e sirva.',
    ],
    dicas:
      'Para valorizar na hora de vender, use forminhas de papel firme no modelo 4 pétalas, que abraçam o brigadeiro e dão acabamento de doceria. E prefira chocolate com pelo menos 50% de cacau: é ele que garante o sabor intenso.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Em dias quentes, guarde na geladeira e tire 20 minutos antes de servir.',
  },
  {
    id: 'uva',
    nome: 'Brigadeiro de Uva',
    resumo: 'Uva verde fresquinha envolvida em brigadeiro branco.',
    emoji: '🍇',
    cor: 'linear-gradient(135deg, #b5d99c, #5a8f4a)',
    imagem: '/brigauva.webp',
    fotoReceita: '/receitauva.webp',
    tempo: '35 min + 2h de descanso',
    rendimento: '25 unidades',
    dificuldade: 'Média',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '2 colheres (sopa) de leite em pó, peneirado',
      '1 colher (sopa) de manteiga sem sal',
      '25 uvas verdes sem semente, médias',
      'Açúcar cristal para enrolar',
      'Manteiga para untar',
    ],
    passos: [
      'Com o fogo ainda desligado, misture na panela o leite condensado e o leite em pó peneirado até ficar liso. Junte a manteiga.',
      'Leve ao fogo baixo e cozinhe mexendo sem parar e raspando bem o fundo, por 12 a 14 minutos, até passar um pouco do ponto de brigadeiro: a massa desliza inteira ao inclinar a panela e o fundo fica visível por alguns segundos.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Enquanto isso, lave as uvas, retire os cabinhos e seque uma a uma com papel-toalha. Deixe-as em temperatura ambiente até a hora de usar.',
      'Unte as mãos, pegue cerca de 15 g de massa (uma colher de sopa rasa) e abra na palma da mão. Coloque uma uva no centro e feche, cobrindo bem a fruta.',
      'Enrole, passe no açúcar cristal e coloque em forminhas nº 4.',
    ],
    dicas:
      'Seque muito bem as uvas, porque qualquer umidade faz a massa escorregar. E nunca use a uva gelada: ela forma gotinhas ao sair da geladeira.',
    conservacao:
      'Por ter fruta fresca, deve ficar na geladeira e ser consumido em até 2 dias. Para festas, monte no dia anterior, no máximo.',
  },
  {
    id: 'canela',
    nome: 'Brigadeiro de Canela',
    resumo: 'Aconchegante, com aroma de especiarias.',
    emoji: '🍂',
    cor: 'linear-gradient(135deg, #c98a4b, #7a4a1e)',
    imagem: '/brigacanela.webp',
    fotoReceita: '/receitacanela.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '25 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '1 colher (sopa) de manteiga sem sal',
      '1 colher (chá) de canela em pó',
      '1 pitada de cravo-da-índia em pó',
      '1 pitada de noz-moscada ralada',
      'Manteiga para untar',
    ],
    paraEnrolar: ['½ xícara (chá) de açúcar refinado', '1 colher (chá) de canela em pó'],
    passos: [
      'Com o fogo ainda desligado, misture na panela o leite condensado, a canela, o cravo e a noz-moscada até ficar liso. Junte a manteiga.',
      'Leve ao fogo baixo e cozinhe mexendo sem parar e raspando bem o fundo, por 10 a 12 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Misture o açúcar e a canela da cobertura num prato fundo.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar com canela.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Combina muito com café, o que faz dele uma ótima opção para cestas de café da manhã. Para a cesta, embale em forminhas dentro de uma caixinha fechada, para o açúcar não umedecer.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. O açúcar da cobertura pode umedecer na geladeira, então, se precisar, passe as bolinhas nele de novo antes de servir.',
  },
  {
    id: 'menta',
    nome: 'Brigadeiro de Menta',
    resumo: 'Chocolate com o frescor da menta.',
    emoji: '🌿',
    cor: 'linear-gradient(135deg, #4cc9a0, #1f6f5a)',
    imagem: '/brigamenta.webp',
    fotoReceita: '/receitamenta.webp',
    tempo: '20 min + 2h de descanso',
    rendimento: '25 unidades (15 g)',
    dificuldade: 'Fácil',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '3 colheres (sopa) de chocolate em pó 50%, peneirado',
      '1 colher (sopa) de manteiga sem sal',
      '3 gotas de essência de menta culinária',
      'Chocolate meio amargo ralado para enrolar',
      'Folhinhas de hortelã fresca para decorar (opcional)',
      'Manteiga para untar',
    ],
    passos: [
      'Com o fogo ainda desligado, misture na panela o leite condensado e o chocolate em pó até ficar liso. Junte a manteiga.',
      'Leve ao fogo baixo e cozinhe mexendo sem parar e raspando bem o fundo, por 10 a 12 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por um instante.',
      'Desligue o fogo, espere 2 minutos e junte a essência de menta. Misture bem.',
      'Prove uma pontinha, depois de soprar bem. Se quiser mais frescor, acrescente mais uma gota por vez.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no chocolate ralado.',
      'Coloque em forminhas nº 4 e, se quiser, decore com uma folhinha de hortelã perto da hora de servir.',
    ],
    dicas:
      'Comece com poucas gotas, porque a menta fica forte muito rápido e não tem como voltar atrás. E espere a massa baixar um pouco a temperatura antes de colocar a essência: no calor, o aroma evapora.',
    conservacao:
      'Dura até 3 dias em temperatura ambiente e até 7 dias na geladeira. Com a folhinha de hortelã, decore só na hora de servir, porque ela murcha rápido.',
  },
  {
    id: 'vegano',
    nome: 'Brigadeiro Vegano',
    resumo: 'Sem nenhum ingrediente de origem animal, feito com leite de coco.',
    emoji: '🌱',
    cor: 'linear-gradient(135deg, #7cb342, #3d6b1f)',
    imagem: '/brigavegano.webp',
    fotoReceita: '/receitavegano.webp',
    tempo: '45 min + 2h de geladeira',
    rendimento: '20 unidades (15 g)',
    dificuldade: 'Média',
    ingredientes: [
      '400 ml de leite de coco culinário (o mais cremoso, não a bebida de coco)',
      '¾ de xícara (chá) de açúcar demerara',
      '3 colheres (sopa) de cacau em pó 100%, peneirado',
      '1 colher (sopa) de óleo de coco sem sabor',
      '1 pitada de sal',
      'Granulado vegano ou cacau em pó para enrolar',
      'Óleo de coco para untar',
    ],
    passos: [
      'Numa panela de fundo grosso e larga, misture o leite de coco e o açúcar até dissolver.',
      'Leve ao fogo baixo e cozinhe mexendo de vez em quando, por 25 a 30 minutos, até reduzir para cerca de metade e ficar com consistência de leite condensado, grosso e cor de caramelo claro.',
      'Junte o cacau peneirado, o óleo de coco e o sal. Mexa bem até ficar liso.',
      'Continue cozinhando, agora mexendo sem parar e raspando bem o fundo, por 8 a 10 minutos, até dar o ponto: a massa desliza inteira ao inclinar a panela e o fundo fica visível por alguns segundos.',
      'Transfira para um prato untado com óleo de coco e cubra com filme plástico encostado na superfície. Espere amornar e leve à geladeira por 2 horas.',
      'Unte as mãos com óleo de coco, enrole bolinhas de cerca de 15 g e passe na cobertura.',
      'Coloque em forminhas nº 4 e volte à geladeira até a hora de servir.',
    ],
    dicas:
      'Confira o rótulo do granulado e do leite de coco, porque muitos têm leite ou derivados na composição. Se a massa não firmar depois da geladeira, volte à panela por mais alguns minutos: faltou reduzir.',
    conservacao:
      'Deve ficar sempre na geladeira, porque a gordura do coco amolece em temperatura ambiente. Dura até 5 dias. Na festa, sirva direto da geladeira e evite deixar a bandeja no sol ou no calor.',
  },
  {
    id: 'banana',
    nome: 'Brigadeiro de Banana',
    resumo: 'Banana caramelizada com toque de canela.',
    emoji: '🍌',
    cor: 'linear-gradient(135deg, #f2d16b, #b8862b)',
    imagem: '/brigabanana.webp',
    fotoReceita: '/receitabanana.webp',
    tempo: '35 min + 2h de descanso',
    rendimento: '30 unidades (15 g)',
    dificuldade: 'Média',
    ingredientes: [
      '1 lata de leite condensado (395 g)',
      '2 bananas-nanicas bem maduras, amassadas (cerca de 200 g)',
      '1 colher (sopa) de manteiga sem sal',
      '1 colher (sopa) de açúcar',
      '½ colher (chá) de canela em pó',
      'Manteiga para untar',
    ],
    paraEnrolar: ['½ xícara (chá) de açúcar cristal', '1 pitada de canela em pó (opcional)'],
    passos: [
      'Numa panela de fundo grosso, derreta a manteiga com o açúcar em fogo médio até o açúcar começar a dourar.',
      'Junte a banana amassada e cozinhe mexendo por 5 a 7 minutos, até ela ficar dourada, com cor de caramelo e bem perfumada.',
      'Abaixe o fogo e acrescente o leite condensado e a canela. Misture bem.',
      'Cozinhe mexendo sem parar e raspando bem o fundo, por 15 a 20 minutos. A banana solta água, então demora mais que um brigadeiro comum. O ponto é quando a massa desliza inteira ao inclinar a panela e o fundo fica visível por alguns segundos.',
      'Transfira para um prato untado e cubra com filme plástico encostado na superfície. Deixe esfriar em temperatura ambiente por 2 a 3 horas.',
      'Misture o açúcar cristal com a canela, se for usar.',
      'Unte as mãos, enrole bolinhas de cerca de 15 g e passe no açúcar.',
      'Coloque em forminhas nº 4 e sirva.',
    ],
    dicas:
      'Quanto mais madura a banana, mais doce e perfumado fica o brigadeiro. Use aquela de casca bem pintadinha. A cor da massa fica caramelo-amarronzada: isso é da banana, não é queimado.',
    conservacao:
      'Por ter fruta na massa, guarde na geladeira e consuma em até 4 dias. Em temperatura ambiente, no máximo 1 dia, como na mesa da festa.',
  },
]

export const guia = {
  recheios: [
    {
      id: 'ganache',
      nome: 'Ganache de Chocolate Meio Amargo',
      descricao: 'Firme e intensa, perfeita para rechear.',
      emoji: '🍫',
      cor: 'linear-gradient(135deg, #4a2a17, #1f1108)',
      imagem: '/recheioganache.webp',
      fotoReceita: '/guiaganache.webp',
      tempo: '10 min + 1h de geladeira',
      rendimento: 'Recheia cerca de 30 brigadeiros',
      ingredientes: [
        '100 g de chocolate meio amargo picado (50% a 60% de cacau)',
        '50 g de creme de leite (cerca de ¼ de caixinha)',
      ],
      passos: [
        'Coloque o chocolate picado bem miudinho numa tigela.',
        'Aqueça o creme de leite no micro-ondas por 20 a 30 segundos, até ficar bem quente, mas sem ferver.',
        'Despeje o creme quente sobre o chocolate e espere 1 minuto, sem mexer.',
        'Misture devagar, do centro para as bordas, até ficar liso e brilhante. Se sobrar algum pedacinho, leve ao micro-ondas por 10 segundos e misture de novo.',
        'Cubra com filme plástico encostado na superfície e leve à geladeira por 1 hora, até firmar.',
      ],
      comoUsar:
        'Com uma colher de chá, faça bolinhas de cerca de 5 g de ganache e leve ao congelador por 10 minutos. Depois, achate uma porção de massa de brigadeiro na mão, coloque a bolinha de ganache no centro, feche bem e enrole.',
      dicas:
        'Pique o chocolate bem miudinho, porque pedaços grandes não derretem só com o calor do creme. E nunca deixe cair água na ganache: uma gotinha já faz o chocolate talhar.',
      conservacao:
        'A ganache pura dura até 5 dias na geladeira, em pote fechado. O brigadeiro recheado segue a validade da massa.',
    },
    {
      id: 'creme-avela',
      nome: 'Creme de Avelã Firme',
      descricao: 'Cremoso por dentro, firme o bastante para rechear sem escorrer.',
      emoji: '🌰',
      cor: 'linear-gradient(135deg, #7b4a2d, #4a2a17)',
      imagem: '/recheiofirme.webp',
      fotoReceita: '/guiafirme.webp',
      tempo: '10 min + 40 min de congelador',
      rendimento: 'Recheia cerca de 20 brigadeiros',
      ingredientes: [
        '4 colheres (sopa) de creme de avelã (cerca de 80 g)',
        '2 colheres (sopa) de leite em pó, peneirado',
        '20 g de chocolate ao leite, derretido',
      ],
      passos: [
        'Derreta o chocolate no micro-ondas de 15 em 15 segundos, mexendo entre cada intervalo.',
        'Numa tigela, misture o creme de avelã, o leite em pó e o chocolate derretido até ficar liso.',
        'Leve ao congelador por 30 minutos, até firmar.',
        'Com uma colher de chá, faça bolinhas de cerca de 5 g e coloque num prato forrado com papel-manteiga.',
        'Volte ao congelador por mais 10 minutos antes de usar.',
      ],
      comoUsar:
        'Tire do congelador poucas bolinhas por vez. Achate uma porção de massa de brigadeiro na mão, coloque a bolinha de avelã no centro, feche bem e enrole.',
      dicas:
        'Se a mistura grudar muito na colher, passe a colher em água quente e seque antes de cada bolinha. E trabalhe rápido: o recheio amolece em poucos minutos fora do frio.',
      atencao:
        'Contém avelã, uma oleaginosa com alto risco de alergia. Identifique bem os brigadeiros recheados na mesa de festa.',
      conservacao:
        'As bolinhas de recheio duram até 1 mês no congelador, em pote fechado. Dá para fazer antes e ter sempre pronto. O brigadeiro recheado segue a validade da massa.',
    },
    {
      id: 'doce-de-leite-flor-de-sal',
      nome: 'Doce de Leite com Flor de Sal',
      descricao: 'Recheio de caramelo salgado, com cristais crocantes na mordida.',
      emoji: '🍯',
      cor: 'linear-gradient(135deg, #f4a261, #b5651d)',
      imagem: '/recheiodoce.webp',
      fotoReceita: '/guiadoce.webp',
      tempo: '10 min + 1h de congelador',
      rendimento: 'Recheia cerca de 20 brigadeiros',
      ingredientes: ['100 g de doce de leite (cremoso bem firme, ou de corte)', 'Flor de sal a gosto'],
      // Vários modos de preparo, cada um com título próprio.
      preparos: [
        {
          titulo: 'Modo de preparo com doce de leite cremoso',
          passos: [
            'Forre um prato ou uma assadeira pequena com papel-manteiga.',
            'Com uma colher de chá, faça montinhos de cerca de 5 g de doce de leite sobre o papel, com espaço entre eles.',
            'Leve ao congelador por 1 hora, até ficarem bem firmes.',
          ],
        },
        {
          titulo: 'Modo de preparo com doce de leite de corte',
          passos: [
            'Corte o tablete em cubinhos de cerca de 1 cm.',
            'Não precisa congelar: ele já é firme o suficiente para rechear.',
          ],
        },
      ],
      comoUsar:
        'Achate uma porção de massa de brigadeiro na mão e coloque um pedacinho de doce de leite no centro. Por cima, coloque 2 ou 3 cristais de flor de sal. Feche bem e enrole. Com o cremoso, tire do congelador poucos pedaços por vez, porque eles amolecem rápido.',
      dicas:
        'Combina muito com o brigadeiro de doce de leite, o de chocolate e o gourmet belga. Use pouca flor de sal: a ideia é um toque salgado na mordida, não um brigadeiro salgado.',
      conservacao:
        'Os montinhos congelados de doce de leite cremoso duram até 1 mês no congelador. O brigadeiro recheado segue a validade da massa.',
    },
    {
      id: 'geleia-frutas-vermelhas',
      nome: 'Geleia de Frutas Vermelhas',
      descricao: 'Recheio azedinho que contrasta com o doce da massa.',
      emoji: '🍓',
      cor: 'linear-gradient(135deg, #d63384, #7b1e3a)',
      imagem: '/recheiogeleia.webp',
      fotoReceita: '/guiageleia.webp',
      tempo: '10 min + 1h de congelador',
      rendimento: 'Recheia cerca de 16 brigadeiros',
      ingredientes: [
        '4 colheres (sopa) de geleia de frutas vermelhas (cerca de 80 g)',
        '1 colher (chá) de amido de milho',
        '1 colher (sopa) de água fria',
      ],
      passos: [
        'Numa panelinha, dissolva o amido de milho na água fria até não sobrar nenhum grumo.',
        'Junte a geleia e misture bem.',
        'Leve ao fogo baixo, mexendo sem parar, até ferver e engrossar. Depois que ferver, cozinhe por mais 1 minuto.',
        'Deixe esfriar completamente.',
        'Forre um prato com papel-manteiga e faça gotinhas de cerca de 5 g com uma colher de chá, com espaço entre elas.',
        'Leve ao congelador por 1 hora.',
      ],
      comoUsar:
        'Tire do congelador poucas gotinhas por vez. Achate uma porção de massa de brigadeiro na mão, coloque a gotinha no centro, feche bem e enrole. A geleia fica firme, mas não endurece como gelo: trabalhe rápido.',
      dicas:
        'Combina muito com o brigadeiro branco, o de Ninho e o gourmet belga. Se a geleia tiver sementes, como a de framboesa, passe por uma peneira antes, para o recheio ficar mais liso.',
      conservacao:
        'As gotinhas duram até 1 mês no congelador. O brigadeiro recheado com geleia deve ficar na geladeira e ser consumido em até 4 dias, porque a geleia solta umidade na massa.',
    },
    {
      id: 'recheio-maracuja',
      nome: 'Recheio Cremoso de Maracujá',
      descricao: 'Azedinho e aveludado, contrasta com o doce da massa.',
      emoji: '🍋',
      cor: 'linear-gradient(135deg, #ffd166, #e09f1f)',
      imagem: '/recheiomaracu.webp',
      fotoReceita: '/guiamaracu.webp',
      tempo: '15 min + 1h de congelador',
      rendimento: 'Recheia cerca de 15 brigadeiros',
      ingredientes: [
        '3 colheres (sopa) de leite condensado',
        '30 g de chocolate branco nobre picado',
        '3 colheres (sopa) de suco natural de maracujá, coado (a polpa de cerca de 1 maracujá)',
      ],
      passos: [
        'Numa panelinha, leve o suco ao fogo baixo e deixe reduzir até sobrar cerca de 1 colher (sopa), por 2 a 3 minutos.',
        'Junte o leite condensado e cozinhe mexendo sem parar, por 2 a 3 minutos, até engrossar e o fundo da panela aparecer rapidamente ao passar a espátula.',
        'Desligue o fogo, junte o chocolate branco e mexa até derreter e ficar liso.',
        'Deixe esfriar completamente.',
        'Forre um prato com papel-manteiga e faça gotinhas de cerca de 5 g com uma colher de chá, com espaço entre elas.',
        'Leve ao congelador por 1 hora.',
      ],
      comoUsar:
        'Tire do congelador poucas gotinhas por vez. Achate uma porção de massa de brigadeiro na mão, coloque a gotinha no centro, feche bem e enrole.',
      dicas:
        'Combina muito com o brigadeiro de chocolate tradicional e com o gourmet belga: o azedinho do maracujá corta o doce do chocolate. Também fica ótimo dentro do brigadeiro branco, para quem quer um maracujá ainda mais intenso.',
      conservacao:
        'As gotinhas duram até 1 mês no congelador. O brigadeiro recheado deve ficar na geladeira e ser consumido em até 5 dias.',
    },
  ],
  coberturas: [
    {
      id: 'casquinha-meio-amargo',
      nome: 'Casquinha de Chocolate Meio Amargo',
      descricao: 'Crocante por fora, cremoso por dentro: vira bombom.',
      emoji: '🍫',
      cor: 'linear-gradient(135deg, #3e2614, #1f1108)',
      imagem: '/casquinha.webp',
      fotoReceita: '/cocasquinha.webp',
      tempo: '15 min + 20 min de secagem',
      rendimento: 'Cobre cerca de 25 brigadeiros',
      ingredientes: ['200 g de chocolate meio amargo fracionado, picado'],
      passos: [
        'Deixe os brigadeiros já enrolados, sem cobertura, na geladeira por 20 a 30 minutos. Eles devem estar firmes, mas não congelados.',
        'Coloque o chocolate picado numa tigela funda e estreita, que facilita mergulhar.',
        'Derreta no micro-ondas de 30 em 30 segundos, mexendo entre cada intervalo. Quando restarem só alguns pedacinhos, pare de aquecer e mexa até derreterem com o calor do próprio chocolate.',
        'Mergulhe um brigadeiro por vez, usando um garfo ou um garfinho próprio para bombom. Levante, bata o garfo de leve na borda da tigela para escorrer o excesso.',
        'Deslize o brigadeiro sobre papel-manteiga e deixe secar em temperatura ambiente, por cerca de 20 minutos.',
        'Coloque em forminhas e sirva.',
      ],
      dicas:
        'Para decorar, salpique granulado, castanhas picadas ou flor de sal logo depois de mergulhar, enquanto o chocolate ainda está mole. Se o chocolate começar a engrossar no meio do processo, volte ao micro-ondas por 10 segundos.',
      atencao:
        'Nunca deixe cair água no chocolate, nem de uma colher molhada. Uma gotinha já faz ele empedrar.',
      conservacao:
        'A casquinha protege o brigadeiro, que segue a validade da massa. Guarde em pote fechado, em local fresco. Na geladeira, a casquinha pode perder o brilho, então tire 20 minutos antes de servir.',
    },
    {
      id: 'banho-branco-colorido',
      nome: 'Banho de Chocolate Branco Colorido',
      descricao: 'Casquinha colorida para combinar com o tema da festa.',
      emoji: '🎨',
      cor: 'linear-gradient(135deg, #ffb3d9, #b8a1e6)',
      imagem: '/colorido.webp',
      fotoReceita: '/cocolorido.webp',
      tempo: '15 min + 20 min de secagem',
      rendimento: 'Cobre cerca de 25 brigadeiros',
      ingredientes: [
        '200 g de chocolate branco fracionado, picado',
        'Corante alimentício lipossolúvel (próprio para chocolate), em pó ou líquido',
      ],
      passos: [
        'Deixe os brigadeiros já enrolados, sem cobertura, na geladeira por 20 a 30 minutos. Eles devem estar firmes, mas não congelados.',
        'Coloque o chocolate picado numa tigela funda e estreita.',
        'Derreta no micro-ondas de 15 em 15 segundos, mexendo bem entre cada intervalo. Quando restarem só alguns pedacinhos, pare de aquecer e mexa até derreterem com o calor do próprio chocolate.',
        'Junte o corante aos poucos, com a ponta de um palito, misturando bem antes de acrescentar mais, até chegar na cor desejada.',
        'Mergulhe um brigadeiro por vez com um garfo, bata de leve na borda da tigela para escorrer o excesso e deslize sobre papel-manteiga.',
        'Deixe secar em temperatura ambiente, por cerca de 20 minutos, e coloque em forminhas.',
      ],
      dicas:
        'Os tons pastel, como rosa-bebê, lilás, azul-claro e verde-menta, são os mais bonitos e fáceis de conseguir. Para fazer várias cores, separe o chocolate derretido em tigelinhas e tinja cada uma. Decore com confeitos logo depois de mergulhar, enquanto o chocolate ainda está mole.',
      atencao:
        'Use só corante lipossolúvel, próprio para chocolate. Corante em gel comum ou líquido comum tem água e faz o chocolate empedrar na hora, sem volta. Confira no rótulo.',
      conservacao:
        'A casquinha protege o brigadeiro, que segue a validade da massa. Guarde em pote fechado, em local fresco e longe da luz, porque o sol desbota as cores.',
    },
    {
      id: 'praline',
      nome: 'Praliné de Castanhas',
      descricao: 'Farofa crocante de caramelo para envolver o brigadeiro.',
      emoji: '🥜',
      cor: 'linear-gradient(135deg, #c8a97e, #8a6a44)',
      imagem: '/castanha.webp',
      fotoReceita: '/cocastanha.webp',
      tempo: '20 min + 20 min para esfriar',
      rendimento: 'Cobre cerca de 25 brigadeiros',
      ingredientes: [
        '½ xícara (chá) de açúcar refinado',
        '½ xícara (chá) de castanhas picadas (amendoim, castanha-de-caju ou nozes)',
        'Óleo ou manteiga para untar',
      ],
      passos: [
        'Torre as castanhas numa frigideira seca, em fogo baixo, mexendo sempre, por 3 a 5 minutos, até ficarem perfumadas e levemente douradas. Reserve ainda quentes.',
        'Forre uma assadeira com papel-manteiga e unte bem.',
        'Numa panela de fundo grosso, espalhe o açúcar e leve ao fogo baixo. Não mexa com colher: quando começar a derreter pelas bordas, apenas gire a panela para o açúcar derreter por igual.',
        'Quando o caramelo estiver todo líquido e cor de mel escuro, desligue o fogo e junte as castanhas quentes. Misture rápido com uma espátula de silicone.',
        'Despeje imediatamente sobre o papel-manteiga e espalhe numa camada fina.',
        'Deixe esfriar por cerca de 20 minutos, até endurecer completamente.',
        'Quebre em pedaços e triture grosseiramente, com um rolo de massa dentro de um saco plástico ou no pilão.',
        'Passe os brigadeiros enrolados na farofa, pressionando levemente para aderir.',
      ],
      dicas:
        'Não deixe o caramelo escurecer demais: do cor de mel escuro para o queimado é questão de segundos, e caramelo queimado fica amargo. Combina muito com o brigadeiro de doce de leite, o de chocolate e o gourmet belga.',
      atencao:
        'O caramelo fica extremamente quente e gruda na pele. Faça longe de crianças, não prove com o dedo e tenha uma tigela de água fria por perto, caso respingue. Todas as opções de castanha são alérgenos fortes: identifique bem na mesa de festa.',
      conservacao:
        'O praliné triturado dura até 2 semanas em pote bem fechado, fora da geladeira. Nos brigadeiros, ele absorve umidade e amolece com o tempo, então passe as bolinhas nele no mesmo dia em que for servir, e não guarde na geladeira.',
    },
    {
      id: 'crocante-arroz',
      nome: 'Crocante de Arroz Tufado',
      descricao: 'Pedacinhos de chocolate com arroz crocante, para dar textura ao brigadeiro.',
      emoji: '🍚',
      cor: 'linear-gradient(135deg, #b07a4a, #6b4423)',
      imagem: '/arroz.webp',
      fotoReceita: '/coarroz.webp',
      tempo: '10 min + 20 min de secagem',
      rendimento: 'Cobre cerca de 25 brigadeiros',
      ingredientes: [
        '1 xícara (chá) de arroz tufado (arroz crocante)',
        '50 g de chocolate ao leite fracionado, picado',
      ],
      passos: [
        'Derreta o chocolate no micro-ondas de 15 em 15 segundos, mexendo entre cada intervalo, até ficar liso.',
        'Junte o arroz tufado e misture delicadamente, até todos os grãos ficarem envolvidos no chocolate.',
        'Espalhe numa camada fina sobre uma assadeira forrada com papel-manteiga.',
        'Deixe secar em temperatura ambiente por 20 minutos, ou na geladeira por 10 minutos, até endurecer.',
        'Quebre com as mãos em pedacinhos bem pequenos.',
        'Passe os brigadeiros enrolados no crocante, apertando de leve para grudar.',
      ],
      dicas:
        'Os pedacinhos precisam ser bem pequenos, do tamanho de um grão de arroz tufado, senão não aderem ao brigadeiro. Combina muito com o brigadeiro tradicional, o de Ninho e o de biscoito recheado.',
      conservacao:
        'O crocante sozinho dura até 1 semana em pote bem fechado, fora da geladeira. Nos brigadeiros, ele perde a crocância com a umidade da massa, então aplique no mesmo dia em que for servir.',
    },
    {
      id: 'acucar-cintilante',
      nome: 'Açúcar Cintilante',
      descricao: 'Brilho delicado para festas elegantes.',
      emoji: '✨',
      cor: 'linear-gradient(135deg, #f5d98b, #c9a24a)',
      imagem: '/acucar.webp',
      fotoReceita: '/coacucar.webp',
      tempo: '5 min',
      rendimento: 'Cobre cerca de 25 brigadeiros',
      ingredientes: [
        '½ xícara (chá) de açúcar cristal',
        '1 colher (chá) de pó para decorar comestível (dourado, prata ou rosé)',
      ],
      passos: [
        'Num prato fundo, misture bem o açúcar e o pó para decorar, até o brilho ficar distribuído por igual.',
        'Passe os brigadeiros enrolados na mistura, girando para cobrir por inteiro.',
        'Misture o açúcar de novo a cada 5 ou 6 brigadeiros, porque o pó tende a ir para o fundo.',
        'Coloque em forminhas e sirva.',
      ],
      dicas:
        'Para um brilho mais intenso, passe o brigadeiro primeiro no açúcar cristal puro e depois, com um pincel seco e macio, aplique o pó para decorar só por cima. Fica lindo em casamentos, aniversários de 15 anos e festas elegantes, principalmente com o brigadeiro branco ou o gourmet belga.',
      atencao:
        'Use somente pó com "comestível" escrito no rótulo. Produtos marcados apenas como "atóxico" ou "decorativo" não são próprios para consumo e não devem ir em doces que serão comidos.',
      conservacao:
        'A mistura de açúcar cintilante dura meses em pote bem fechado. Nos brigadeiros, o açúcar pode umedecer na geladeira, então, se precisar, passe as bolinhas de novo antes de servir.',
    },
  ],
}

// Para adicionar áudio, coloque o arquivo em public/ e informe "audio": "/episodio-1.mp3".
export const podcasts = [
  {
    id: 'ep1',
    titulo: 'Fundamentos do brigadeiro gourmet',
    descricao: 'Ponto certo, ingredientes de qualidade e os erros mais comuns.',
    duracao: '3 min',
    audio: '/Fundamentos.mp3',
  },
  {
    id: 'ep2',
    titulo: 'Como precificar seus doces',
    descricao: 'Custo dos ingredientes, tempo de trabalho e margem de lucro.',
    duracao: '3 min',
    audio: '/precificar.mp3',
  },
  {
    id: 'ep3',
    titulo: 'Embalagens que vendem',
    descricao: 'Caixas, forminhas e apresentação para encantar o cliente.',
    duracao: '3 min',
    audio: '/embala.mp3',
  },
]
